apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      containers:
      - args:
        - elasticsearch
        - -Des.cluster.name=graylog
        image: elasticsearch:2
        name: elasticsearch
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      service: elasticsearch
