apiVersion: v1
kind: Service
metadata:
  labels:
    service: graylog
  name: graylog
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "12201"
    port: 7000
    targetPort: 7000
  selector:
    service: graylog
